### ISSUE TITLE
Fails on HA 2024.12.1

### ISSUE THREAD

**Issue by nshores** [rarosalion/authenticated#3]
**Version of the custom_component**
0.0.1

**Describe the bug**
Fails to setup integration on 2024.12.1
**log**

```
Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:366
integration: Sensor
First occurred: 3:07:29 PM (1 occurrences)
Last logged: 3:07:29 PM

Error while setting up authenticated platform for sensor
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/requests/models.py", line 974, in json
    return complexjson.loads(self.text, **kwargs)
           ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/simplejson/__init__.py", line 514, in loads
    return _default_decoder.decode(s)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/usr/local/lib/python3.13/site-packages/simplejson/decoder.py", line 386, in decode
    obj, end = self.raw_decode(s)
               ~~~~~~~~~~~~~~~^^^
  File "/usr/local/lib/python3.13/site-packages/simplejson/decoder.py", line 416, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
           ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 366, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/authenticated/sensor.py", line 85, in setup_platform
    sensor.initial_run()
    ~~~~~~~~~~~~~~~~~~^^
  File "/config/custom_components/authenticated/sensor.py", line 164, in initial_run
    ipaddress.lookup()
    ~~~~~~~~~~~~~~~~^^
  File "/config/custom_components/authenticated/sensor.py", line 409, in lookup
    geo = get_geo_data(self.ip_address, self.provider)
  File "/config/custom_components/authenticated/sensor.py", line 300, in get_geo_data
    geo_data.update_geo_info()
    ~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/config/custom_components/authenticated/providers.py", line 55, in update_geo_info
    data = requests.get(api, headers=header, timeout=5).json()
  File "/usr/local/lib/python3.13/site-packages/requests/models.py", line 978, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by Shaun-Harrison** [comment]
Seeing this also

**Comment by rarosalion** [comment]
I think this should work now with v0.0.2. Let me know if you have further issues.

**Comment by rarosalion** [comment]
Verified working now for me with v0.0.2 on 2025.1.0
